### ISSUE TITLE
Can't pull images from artifact registry

### ISSUE THREAD

**Issue by SimonCaignart** [murphye/cheap-gke-cluster#10]
When trying to deploy an application I am getting image pullback off. The docker image is stored in Google Artifact Registry. Normally the compute engine default service account has read access to storage in the same project.

Is there something different with this configuration ?

**Comment by murphye** [comment]
The GKE cluster is a private cluster. That is why I had to use a NAT Gateway to pull from Docker Hub. I will investigate this issue you say in pulling from Google Artifact Registry... rather odd.

**Comment by murphye** [comment]
I found an article on this. Seems to be a pain to configure! I am surprised the NAT Gateway doesn't resolve this. I'll research more.

https://cloud.google.com/vpc-service-controls/docs/set-up-gke

**Comment by murphye** [comment]
Command to test connectivity:

```
kubectl create deployment hello-server --image=us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
```

**Comment by murphye** [comment]
Additional doc: https://cloud.google.com/artifact-registry/docs/integrate-gke


> If GKE is in a different project than Artifact Registry, grant Artifact Registry permissions to the service account that your GKE node use. By default, nodes use the Compute Engine default service account.

**Comment by murphye** [comment]
I was able to reproduce this issue. This was the fix. Thanks for reporting!

https://github.com/murphye/cheap-gke-cluster/blob/main/terraform/gke.tf#L46
