### ISSUE TITLE
Error on deploy gloo 

### ISSUE THREAD

**Issue by ricardotjr** [murphye/cheap-gke-cluster#9]
Plan: 5 to add, 0 to change, 0 to destroy.
helm_release.gloo: Creating...
╷
│ Error: failed to download "https://storage.googleapis.com/solo-public-helm/charts/gloo-1.10.2.tgz"
│ 
│   with helm_release.gloo,
│   on gloo.tf line 11, in resource "helm_release" "gloo":
│   11: resource "helm_release" "gloo" {
│ 
╵

**Comment by alkanna** [comment]
```helm repo add gloo https://storage.googleapis.com/solo-public-helm
helm repo update```

**Comment by murphye** [comment]
I have received feedback from another person on the Helm module for Terraform. It seems to be flaky, even though it always worked great for me!

I am going to replace it with running the helm commands locally. Stay tuned!

**Comment by murphye** [comment]
Fixed with depends_on

**Comment by ricardotjr** [comment]
> I have received feedback from another person on the Helm module for Terraform. It seems to be flaky, even though it always worked great for me!
> 
> I am going to replace it with running the helm commands locally. Stay tuned!

success...... tks
